### ISSUE TITLE
SETUP of new install from Master Fails

### ISSUE THREAD

**Issue by tmccormi** [LibreHealthIO/lh-ehr#1127]
sqlconf.php is not missing from /sites/default  so setup.php fais when it checks.

Setup would create it (I believe), but currently it can't get past the "Is it writeable step".

This was apparently removed and merged without proper testing.

db92b73 MIPS module refactor (#1102)
M       sites/default/menu_data.json
D       sites/default/sqlconf.php

**Comment by aethelwulffe** [comment]
It was dropped at the last moment, as I believed it had already been deleted from the repo (due to you stating quite a while ago that this was your intent), and obviously my test instance had a copy.

How about I do a PR that actually gets us past this piece?

**Comment by aethelwulffe** [comment]
Interesting notes:
ZEND configuration is still all over the place.
Setup references style_sky_blue.css
A TODO remove comment on some site directory called CVS

QUESTION:  Is there any reason, seeing as the installer creates the file anyway, and sets the permissions, to not simply bypass the check for the config file completely?  I am not seeing any reason to remove any other conditional statements associated with the process.

I am testing this state now.

**Comment by aethelwulffe** [comment]
Lots of Chicken and Egg stuff with the setup file and the sqlconf.php.
Quick solution, I can push a PR with a copy of the file.  Second, I have a branch here:
https://github.com/LibreHealthIO/lh-ehr/compare/Setup-Legacy-Remove
where I am doing a bit more, experimentally at least.
1.  Setup/index needs an installation state configuration.
case 0 = normal mode, no sites installed.
case 1 = normal mode, sites installed.
case 2 = developer mode, fewer checks for localhost vs mysql root password requirements etc..

2.  setup.php remains...dangerous.  localhost access could be checked more specifically, but allowing setup to run against a known and existing site directory is hinky.

3.  The /default site destination can be bypassed and installers can easily be routed through the full setup process required by second site installations by disallowing the use of the /default site (if not already configured).  The problem is that you then must always pass your site id with the URL.  This isn't that big of an inconvenience, and can be handled in other ways, but it does kill the myurl.dom/libreehr simple access you get when using the /default site directory.  An alternative is to allow configuration redirection with a site_list.php file for easier access when no site is appended to the URL.

Perhaps none of the above will be relevant when the GSOC team hits this.

**Comment by aethelwulffe** [comment]
#1128 or I can just put back the config file..(gross).
