### ISSUE TITLE
Erratic behavior on resizing tabs

### ISSUE THREAD

**Issue by abhigyank** [LibreHealthIO/lh-ehr#956]
Mentioned in #954 .

Behavior:
On log-in, rightmost tab has resize tooltip.
Add third tab, and the rightmost no-longer has tooltip.
Open fourth tab, and only the left two are resizable.
Close the two left tabs, and none of the remaining are resizable.
Open or close any tabs, yet never get your resize back.

**Comment by Trodrige** [comment]
@abhigyank have you looked into this? I was able to reproduce this behaviour.

**Comment by aethelwulffe** [comment]
I think we have at least one other issue related to this.

**Comment by apooravc** [comment]
@aethelwulffe I think the problem is in `main.php`. At line `142`, there is a plugin for resizing. The spaces b/w tabs where the resize icon appears is a `div` with a class of `handle` and at line `211`, all such elements are selected and passed to `drags` function at line `143`, which is the resize jquery plugin. It contains a `mousedown` event so that when you click on the space `div` and drag it, it resizes. 

Now, the issue is that somehow `drags` is called only for spaces `div` next to the first two tabs which first appear on logging in. And then it is never called for spaces `div` next to tabs opening after the first two tabs, which explains the behavior mentioned above. Any thoughts?

**Comment by aethelwulffe** [comment]
I can just state that the original designer intended us to never have more than two tabs open at the same time.  In that context, it functions perfectly.  It just isn't as useful.

So, it might be that the resizing plugin needs a full implementation refactor to actually fix this.  We are outside of the intended architecture.
